name: briteminds
favicon: null
layout_spectrum: 0
typography_spectrum: 0.90462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.886243226705119
  lightness: 0.27483234158717096
  saturation: 0.14351203409023583
  rhythmicContrast: 0.4149709327612072
purpose: []
